/*
 * Liquid glass lens: an SVG filter for `backdrop-filter` that bends what is
 * behind a surface at its rim (refraction), keeps the middle frosted, and
 * catches a fixed top-left light on the curved rim (reflection).
 *
 * Chrome does not load images (feImage) inside backdrop-filter, so the
 * displacement map is generated by the filter itself: a blurred rectangle is
 * the glass "height", and its slope, h(x - d) - h(x + d), built from two
 * feOffsets and one arithmetic composite, drives feDisplacementMap. In
 * Chrome a map value below 0.5 on the left rim samples inward, which makes the
 * rim magnify like a convex glass edge.
 *
 * The filter is laid out in the element's own CSS pixels (userSpaceOnUse). It
 * must be used on a layer with no outer box-shadow: Chrome measures a
 * backdrop filter's coordinates from the shadow's outer edge, which would
 * shift the map off the element. The engine therefore puts it on ::before.
 *
 * Large surfaces only bend within a thin rim, so their costly steps run on four
 * edge strips and the middle is one plain blur.
 */

const SVG_NS = 'http://www.w3.org/2000/svg';
const GREY = '0 0 0 1 0  0 0 0 1 0  0 0 0 1 0  0 0 0 0 1'; // alpha -> opaque grey
// The rim weight 1 - h, in colour and alpha (premultiplied grey).
const INV_WEIGHT = '0 0 0 -1 1  0 0 0 -1 1  0 0 0 -1 1  0 0 0 -1 1';
const R_ONLY = '1 0 0 0 0  0 0 0 0 0.5  0 0 0 0 0.5  0 0 0 0 1';
// One colour channel each, alpha kept: for the colour split at the rim.
const CHANNEL = {
  R: '1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0',
  G: '0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0',
  B: '0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0',
};
const G_ONLY = '0 0 0 0 0.5  0 1 0 0 0  0 0 0 0 0.5  0 0 0 0 1';
const LARGE = 140; // shorter side above this: rim-strip filter

const node = (tag, attrs, kids = []) => {
  const n = document.createElementNS(SVG_NS, tag);
  for (const [k, v] of Object.entries(attrs)) n.setAttribute(k, String(v));
  kids.forEach((k) => n.appendChild(k));
  return n;
};
const box = (x, y, width, height) => ({ x, y, width, height });
const invert = () => ['R', 'G', 'B'].map((c) => node(`feFunc${c}`, { type: 'linear', slope: -1, intercept: 1 }));

/**
 * Builds the filter element for a w x h surface.
 * @param {number} w, h   surface size in CSS px
 * @param {number} frost  blur of the frosted middle, px
 * @param {string} id     filter id
 * @param {number} disp   colour split: blue bends this much more than green,
 *                        red this much less (0 = none)
 */
export function buildLensFilter(w, h, frost, id, disp = 0) {
  const m = Math.min(w, h);
  const sigma = Math.max(4, Math.min(12, m * 0.2));         // how far in the glass curves
  const d = Math.max(2, Math.round(sigma * 0.6));            // slope sampling distance
  const scale = Math.max(16, Math.min(70, m * 0.9));         // how strongly the rim bends
  const rim = Math.min(Math.ceil(sigma * 2.6 + d), Math.floor(m / 2));
  const full = box(0, 0, w, h);

  const f = node('filter', {
    id, ...full, filterUnits: 'userSpaceOnUse', primitiveUnits: 'userSpaceOnUse', 'color-interpolation-filters': 'sRGB',
  });
  const add = (tag, attrs, kids) => f.appendChild(node(tag, attrs, kids));

  // The glass height: 0 at the very edge rising to 1 inside, and the frost.
  add('feFlood', { 'flood-color': '#fff', ...full, result: 'rect' });
  add('feGaussianBlur', { in: 'rect', stdDeviation: sigma, ...full, result: 'soft' });
  add('feGaussianBlur', { in: 'SourceGraphic', stdDeviation: frost, edgeMode: 'duplicate', ...full, result: 'frost' });

  // Small surfaces are one region; large ones four rim strips over the frost.
  const regions = m > LARGE
    ? { t: box(0, 0, w, rim), b: box(0, h - rim, w, rim), l: box(0, rim, rim, h - 2 * rim), r: box(w - rim, rim, rim, h - 2 * rim) }
    : { a: full };

  const outs = [];
  for (const [s, reg] of Object.entries(regions)) {
    if (reg.width <= 0 || reg.height <= 0) continue;
    const slope = (axis) => {
      const back = axis === 'x' ? { dx: d, dy: 0 } : { dx: 0, dy: d };     // h(p - d)
      const ahead = axis === 'x' ? { dx: -d, dy: 0 } : { dx: 0, dy: -d };  // h(p + d)
      add('feOffset', { in: 'soft', ...back, ...reg, result: `${s}${axis}a0` });
      add('feColorMatrix', { in: `${s}${axis}a0`, type: 'matrix', values: GREY, ...reg, result: `${s}${axis}a` });
      add('feOffset', { in: 'soft', ...ahead, ...reg, result: `${s}${axis}b0` });
      add('feColorMatrix', { in: `${s}${axis}b0`, type: 'matrix', values: GREY, ...reg, result: `${s}${axis}b1` });
      add('feComponentTransfer', { in: `${s}${axis}b1`, ...reg, result: `${s}${axis}b` }, invert());
      // 0.5 + 0.5 * (h(p - d) - h(p + d)), alpha stays 1
      add('feComposite', { in: `${s}${axis}a`, in2: `${s}${axis}b`, operator: 'arithmetic', k1: 0, k2: 0.5, k3: 0.5, k4: 0, ...reg, result: `${s}${axis}` });
    };
    slope('x');
    slope('y');
    add('feColorMatrix', { in: `${s}x`, type: 'matrix', values: R_ONLY, ...reg, result: `${s}xr` });
    add('feColorMatrix', { in: `${s}y`, type: 'matrix', values: G_ONLY, ...reg, result: `${s}yg` });
    add('feComposite', { in: `${s}xr`, in2: `${s}yg`, operator: 'arithmetic', k1: 0, k2: 1, k3: 1, k4: -0.5, ...reg, result: `${s}map` });
    if (disp > 0) {
      // Real glass bends each colour a little differently, leaving a faint
      // rainbow fringe at the rim: one displacement per channel, summed.
      ['R', 'G', 'B'].forEach((c, i) => {
        add('feDisplacementMap', { in: 'SourceGraphic', in2: `${s}map`, scale: scale * (1 + (i - 1) * disp), xChannelSelector: 'R', yChannelSelector: 'G', ...reg, result: `${s}d${c}` });
        add('feColorMatrix', { in: `${s}d${c}`, type: 'matrix', values: CHANNEL[c], ...reg, result: `${s}c${c}` });
      });
      add('feComposite', { in: `${s}cR`, in2: `${s}cG`, operator: 'arithmetic', k1: 0, k2: 1, k3: 1, k4: 0, ...reg, result: `${s}rg` });
      add('feComposite', { in: `${s}rg`, in2: `${s}cB`, operator: 'arithmetic', k1: 0, k2: 1, k3: 1, k4: 0, ...reg, result: `${s}bent` });
    } else {
      add('feDisplacementMap', { in: 'SourceGraphic', in2: `${s}map`, scale, xChannelSelector: 'R', yChannelSelector: 'G', ...reg, result: `${s}bent` });
    }

    // Bent at the rim, fading out inward: bent * (1 - w), with the weight in
    // alpha too, laid over the frost. The frost is read only once, over the
    // whole surface: Chrome blurs it again, cropped, for each strip that
    // reads it, which came out brighter than the middle and left a seam.
    add('feColorMatrix', { in: 'soft', type: 'matrix', values: INV_WEIGHT, ...reg, result: `${s}iw0` });
    // sqrt keeps the bend visible further in before it fades into the frost.
    add('feComponentTransfer', { in: `${s}iw0`, ...reg, result: `${s}iw` },
      ['R', 'G', 'B', 'A'].map((c) => node(`feFunc${c}`, { type: 'gamma', amplitude: 1, exponent: 0.5, offset: 0 })));
    add('feComposite', { in: `${s}bent`, in2: `${s}iw`, operator: 'arithmetic', k1: 1, k2: 0, k3: 0, k4: 0, ...reg, result: `${s}rim` });

    // Reflection: a fixed light from the top-left on the curved rim, masked by
    // the same weight so the frosted middle gets no light at all.
    add('feSpecularLighting', {
      in: 'soft', surfaceScale: 6, specularConstant: 0.9, specularExponent: 60, 'lighting-color': '#fff', ...reg, result: `${s}spec`,
    }, [node('feDistantLight', { azimuth: 225, elevation: 40 })]);
    add('feComposite', { in: `${s}spec`, in2: `${s}iw`, operator: 'arithmetic', k1: 0.6, k2: 0, k3: 0, k4: 0, ...reg, result: `${s}shine` });
    outs.push(`${s}rim`, `${s}shine`);
  }

  add('feMerge', { ...full }, [node('feMergeNode', { in: 'frost' }), ...outs.map((n) => node('feMergeNode', { in: n }))]);
  return f;
}
